### ISSUE TITLE
Wrap a callback?

### ISSUE THREAD

**Issue by tadfisher** [tikurahul/kotlin-futures#2]
Guava has a nice class called [`SettableFuture`](https://google.github.io/guava/releases/20.0/api/docs/com/google/common/util/concurrent/SettableFuture.html) which allows one to fairly easily wrap a callback with a Future:

```kotlin
fun doSomething(): Future<Result> {
  val future = SettableFuture.create<Result>()
  longRunningTask { result -> future.set(result) }
  return future
}
```

Is there an easy way to do this with this library? I'd rather not depend on Guava.

**Comment by tikurahul** [comment]
Yes, there is. You are talking about `resolving` a future. There is a handy method defined [here](https://github.com/tikurahul/kotlin-futures/blob/master/src/main/kotlin/com/rahulrav/futures/Futures.kt#L140).

You should be able to do something like:

```kotlin
fun doSomething(): Future<Result> {
    // the thread pool you want to use for dispatching calls to onSuccess(), or onError().
    val executor = Executors.newSingleThreadExecutor()
    val future = Future<Result>(executor)
    longRunningTask { result -> future.resolve(result) }
}
```

There is also a handy method for [rejecting](https://github.com/tikurahul/kotlin-futures/blob/master/src/main/kotlin/com/rahulrav/futures/Futures.kt#L150) a `Future` (on an exception).

I should also expose a no-args convenience constructor, that uses the [defaultExecutor](https://github.com/tikurahul/kotlin-futures/blob/master/src/main/kotlin/com/rahulrav/futures/Futures.kt#L273) used by the library.

Hope this helps.

**Comment by tikurahul** [comment]
Added another convenience constructor. With that change (once you point to the latest version of the library) you should be able to do:

```kotlin
fun doSomething(): Future<Result> {
    val future = Future<Result>()
    longRunningTask { result -> future.resolve(result) }
    return future
}
```

**Comment by tadfisher** [comment]
Perfect, thanks!
